name: Jekyll Begin
markdown: redcarpet
#pygments: false
highlighter: pygments 

source: ./jekyll
destination: ./site

contact:
  phone: 800-865-3625
  email: blah@gmail.com
  pobox: PO Box 23 - Amsterdam, NY 12010

social:
  twt: 
  fb:
  li: https://www.linkedin.com/company/active-solar-development-llc

cert:
  nab:
  bpi:
  poly:

# change baseurl to:
# '': for root level domains ie: mycustomdomain.com
# '/projectname': for subdomains ie: user.github.io/projectname
baseurl: '/ActiveSolar'
permalink: :title.html

exclude: ["js/*",'img/*','scss/*','package.json','config.rb','bower.json','Gruntfile.js','node_modules/*','.jekyll-assets-cache/*','site/*','.sass-cache/*','bower_components/*','jekyll/*']
# include: ['../bower_components/']

#minfy_html: false


# assets:

#   sources:
#     - _assets/fonts
#     - _assets/images
#     - _assets/javascripts
#     - _assets/stylesheets


  # cache: false
  # # js_compressor:  uglifier
  # css_compressor: sass
  # baseurl: assets/


# jekyll-press:
#   exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   js_options: {}      # js minifier options
#   css_options: {}     # css minifier options
#   html_options: {}    # html minifier options

banner:
  solarelectric:'https://assets.nerdwallet.com/blog/finance/files/2012/08/solar-panels.png'
  Solar Hot Water:'https://assets.nerdwallet.com/blog/finance/files/2012/08/solar-panelss.png'